### ISSUE TITLE
curvatures.at<DATA_TYPE>(x, y, 1) cross the border

### ISSUE THREAD

**Issue by sunjunlishi** [konalio/FingerVeinRecognition#1]
curvatures.at<DATA_TYPE>(x, y, 1)   cross the border

**Comment by caiyanhuang** [comment]
the code has bug,how do you solve it?

**Comment by pkupidura** [comment]
I'm sorry, but currently I don't have time to do any fixes to this project - it was research during my university time. I hope you understand. Good luck!
